env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
parser: '@typescript-eslint/parser'
plugins: 
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
